---
title: Does the infrastructure of Amsterdam make a difference?
author: 
- "Francisco Riaño Martinez, Jan van der Doe, Kamila Majdlenová, Pomme Verhagen, Yuetong Bi"
date: 27.03.2022
output: pdf_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(rlist)
library(modelsummary)
```

## Introduction

Do factors like distance to/from tram stops, metro stops, central station, swimming pools, religious sites, parks, Schiphol airport, sport facilities influence the prices of AirBnB listings in Amsterdam? And does the effect of the several infrastructure components on AirBnB pricing differ depending on whether there is a holiday/weekend or not?

### Motivation

Infrastructure is the key to developing a successful tourism destination. Tourism industry stimulates investments in new infrastructure, most of which improves the living conditions of local residents as well as tourists.The reason for diving into this research is that the distances to transportation hubs and busy areas are important considerations for tourists when choosing an accommodation. Also other infrastructure components like swimming pools, sport facilities, religious sites or parks can be factors which improve the living conditions of local residents as well as tourists. These components are for some people of vital importance in choosing a place to stay. While Airbnb plays an important role in the tourism industry of today, infrastructure components might influence prices of Airbnb listings accordingly. Moreover, the holiday season and weekends can be contributing factors to prices of AirBnB listings because the demand for accomodations increases. Therefore questions like: 'Does the distance to/from Amsterdam Central Station or the distance to/from Schiphol Airport in relation to the location of the Airbnb listing influence the prices of that Airbnb listing?' and 'does the effect of the several infrastructure components on AirBnB pricing differ depending on whether there is a holiday/weekend or not? could be asked. This code is written in order to find answers to these questions which focuses on Airbnb listings in Amsterdam.

## Background

## Data

The data used in this project comes from the website insideairbnb.com which is an open source activist project that provides publicly available data from AirBnB. Moreover,infrastructure information was collected from the city of Amsterdam website at maps.amsterdam.nl. Lastly, a new dataset was created with Dutch holidays.

### Data Collection

This research focuses on price analysis of AirBnB in Amsterdam, the Netherlands between years 2012 and 2019. Therefore, only data from Amsterdam in 2012-2019 is downloaded form the website, namely, listings and calendar information. The downloaded files were stored in Google Drive to ensure the same dataset can also be accessed in the future. To download the data see data/download_data.R.

### Data Processing

Several steps were taken in order to create a final dataset that will be used throughout the analysis. Firstly, in the holidays dataset a new variable "weekend" was created. Next, the datasets listings, distance, calendar and holidays were joined together creating a new merged dataset. Furthermore, two new constructs per each infrastructure point of interest were created. The first variable calculates the distance from each accommodation to metro, tram, swimming pool, Schiphol airport, Central station, place of religion, park, sport facilities. The second variable states how many of the eight above mentioned infrastructure measures can be found within 500 meters. The last step was to clean the data, during which missing values were reviewed and price variables were converted from character to numeric type. The final cleaned dataset that will be used for the analysis was saved to folder gen/output.

## Methodology

The research method that is used in this project is a regression analysis. This method is used to predict the influence of the independent variables 'Distance to/from tram stops', 'Distance to/from metro stops', 'Distance to/from Amsterdam Central Station', 'Distance to/from swimming pools', 'Distance to/from religious sites', 'Distance to/from parks', 'Distance to/from Schiphol Airport' and 'Distance to/from sport facilities' on the dependent variable 'Prices of Airbnb listings'. Furthermore the moderators 'Holidays in NL' and 'Weekend' will be included and analyzed. According to this model, the research questions can be answered.

## Results

In this paper, we study the several infrastructures factors affecting the price of Airbnb listings and calculate the correlation between the four variables of price, adjusted price, cs_disct (distance to/from AMS central station), and holiday by rcorr(type="spearman") function to calculate the Spearman correlation coefficients between the response variables.

By plotting the graphs between the variables schiphol_dist (distant to/from Schiphol airport), tram_dist (distance to tram stops), metro_dist (distance to/from metro stops), cs_dist (distance to/from AMS central station), swim_dist (distance to/from swimming pool), religion_dist (distance to/from the places of religion), park_dist (distance to/from park), and sport_dist (distance to/from sport facilities) and price to visualize a general overview of their correlations.

According to the plots it can be found that schiphol_dist is positively correlated with price, while the rest of the independent variables are negatively correlated with price. Since the value of dist is particularly large, the log() function is used to process the value for visualization again in order to prevent the influence of the huge value on the model.

Based on further visualization, it can be found that price around 175 is a significant inflection point that change the direction. To be more specific, the listings with prices below 175 showing opposite results to those with prices above 175. For listings priced less than 175, there is a positive correlation between price and each variable. For the listings with price greater than 175, the relationship between price and the variables shows a negative relationship.

It can also be concluded that the infrastructure is often related to the distance. For further research, this paper analyzes the number of metros, airports, AMS central stations, etc. within a 500-meter radius, and uses slice_sample(n=100000) to extract data from a sample of 100,000, uses the total ASE function of ggplot to map the x-axis and y-axis, and uses the geom_col() function to draw a histogram. According to the histogram of the number of each infrastructure and the price of the neighborhood within 500 meters, it can be found that the number conforms to the right-hand side normal distribution with a mean value of 0, and most of the numbers are distributed in the range of 0 to 3.

Our study also considers the correlation between independent variables, the possible interaction factors would affect the result.  We set weekend and holidays (dummy variables) as two moderators and establish a model_ poly_ log_ Int multiple regression model.

Based on the results of summary of multiple regression model (model_ poly_ log_ Int), it can be shown that most of the variables are set within the 99.9% confidence interval, indicating that these variables have a significant correlation with price. The adjusted R square shows that how much variation of price of Airbnb is explained by the independent variables of infrastructure factors in the regression model. The adjusted R is 0.05734, which means multiple regression model is a good fit, that proves the effectiveness of the model. Through this model we can predict the price of Airbnb according to the different value of independent variables.

## Conclusion
As a conclusion to our model can be stated that every distance-variable (Schiphol Airport, Central Station, tram stops, metro stops, swimming pools, religious sites, parks, sport facilities) have a significant effect on the prices of AirBnB listings, whereas the interaction effect of holiday and weekend show no significant effect on the model. This explains that distances from and to important infrastructure sites play an important role in the price setting of AirBnB listings. The positive inflection point with regards to the distance to/from schiphol airport could be due to the fact of noise pollution of the airport. It can be concluded that residents and tourists of Airbnb listings don't want to be as close to the infrastructure (in particular for Schiphol) while also staying not too far away. Hence, the postive inflection point at a price of 175. In the distance plots of cs, tram, metro and religion sites, a small increase at first is followed by a negative relationship between the distances and the prices of Airbnb. This can also be related to the fact of noises nearby the Airbnb listings while at the same time being mobile and staying close to the infrastructure sites. Parks, swimming pools and sport facilities show an immediate negative relationship between the distances of these infrastructure sites and the prices of Airbnb listings. This indicates the importance of these infrastructures sites nearby the Airbnb listings. All in all, the closer the infrastructure sites, the higher the prices of Airbnb listings (except for Schiphol airport). This shows that tourists and residents value the infrastructure sites to be nearby Airbnb listings which in turn drives prices up. 


### Managerial Relevance
Prices of AirBnb accommodation vary across cities and countries. There are various factors that can play a role in the price setting but this study focuses on the infrastructure as it is a crucial aspect when deciding where to travel. If the the analysis shows that living close to certain kind of infrastructure leads to higher price, these insights can be further used by the management of Airbnb as well as the host for more effective price setting. Public policy makers can also benefit from this research. If there is a significant effect of infrastructure on pricing, they should invest in developing and improving it.

### Limitations and Future Directions of Research

This study also has some limitations. The research was geographically limited to Amsterdam so future studies could focus on different countries or cities to test the generalizability of the results. Moreover, only data collected from AirBnB were analyzed in this study. Thus, focusing on other hospitality providers or another industry might bring interesting results. Furthermore, other factors that likely have effect on price could be included in the future studies. For example, reviews and ratings as well as review sentiment might be driving or influencing the relationship to some extent. Hence, building upon the current study by adding impact of reviews could provide new insights.  

## References
